The documentations are added.
Quarticai/QuarticGym pull request #16
Opened 2022-01-13 11:10 UTC by mohan-zhang-quartic

2022-01-13 15:22 UTC, xiaozhouwang reviewed
I assume the code runs without problem here. Can test that once we merge this and start using it.

2022-01-13 15:22 UTC, xiaozhouwang commented on docs/atropineenv.rst
> +is the states and :math:`\hat{x}(t)` is the estimated. The above linear system
**is the estimated --> **is the estimation

2022-01-13 15:22 UTC, xiaozhouwang commented on docs/atropineenv.rst
> +Also, the Kalman filter is:
--> kalman filter progresses like:

2022-01-13 15:22 UTC, xiaozhouwang commented on docs/atropineenv.rst
> +`SIPPY <https://github.com/CPCLAB-UNIPI/SIPPY>`__. More, since the
More, since the identification process requires training data, we can easily generate the data by the open-loop model. 
-->
And training data can be generated by the open-loop model for the identification process.

2022-01-13 15:22 UTC, xiaozhouwang commented on docs/atropineenv.rst
> +inputs and the output reach the steady-state inputs and output,
the steady-state inputs and output, --> steady-state,

2022-01-13 15:22 UTC, xiaozhouwang commented on docs/atropineenv.rst
> +and MPC control) cost less than 10 seconds.
cost --> takes

2022-01-13 15:22 UTC, xiaozhouwang commented on docs/beerfmtenv.rst
> +Beer is one of the oldest and most widely consumed alcoholic drinks in the world, and we have a lot of ways to produce them. This class provides a typical (and naive) simulation of the industry-level
typical (and naive) --> typical (and simple enough)

2022-01-13 15:22 UTC, xiaozhouwang commented on docs/beerfmtenv.rst
> +To better assist any control algorithms on this simulation, we also provided a . Please consult the 'profile_industrial' in the BeerFMT section `here <https://github.com/Quarticai/QuarticGym/blob/mai
a . ?

2022-01-13 15:22 UTC, xiaozhouwang commented on docs/pensim_challenge.rst
> +Penicillin Control Challenge
do we want to include this in QuarticGym? I feel it is better to be separated from a simulation env.

2022-01-13 15:22 UTC, xiaozhouwang commented on docs/pensimenv.rst
> +sum  very high                 77437.72 (21.51 h)
this is more internal table since it varies a lot depending what BayeOpt package is used. If we want to include this, probably just include the performance. Something like "with bayesian optimization, our experiment shows around 12% improvement for the best run and 4% on average across all batches"

2022-01-13 17:13 UTC, Sile-Tao requested changes

2022-01-13 17:13 UTC, Sile-Tao commented on docs/pensim_challenge.rst
> +It doesn't utilise the 10 random batch and the performance looks much
batch-> batches

2022-01-13 17:13 UTC, Sile-Tao commented on docs/pensim_challenge.rst
> +   generated with Bayesian Optimization as its core.
Bayesian Optimization -> Bayesian Optimization (BayesOpt)

2022-01-13 17:13 UTC, Sile-Tao commented on docs/pensim_challenge.rst
> +Average across all bayeopt frameworks:
bayeopt -> BayesOpt

2022-01-13 17:13 UTC, Sile-Tao commented on docs/atropineenv.rst
> +What is atropine? We can simply treat it as one medication that benefits human beings. A corresponding continuous prodcution flow can be described as below:
prodcution -> production

2022-01-13 17:13 UTC, Sile-Tao commented on docs/atropineenv.rst
> +We generated below trajectory with `MPC <https://en.wikipedia.org/wiki/Model_predictive_control>`_, and ended the simulation once it reaches the steady state (we considered this as a termination cond
generated below trajectory -> generated the below trajectory

2022-01-14 03:11 UTC, Mohan-Zhang-u commented on docs/pensim_challenge.rst
> +Penicillin Control Challenge
sorry I forgot to remove this file... doing it

2022-01-14 15:10 UTC, Sile-Tao approved these changes

2022-01-14 15:12 UTC, merged